apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: renovate 
  title: Add renovate to your repo
  description: |
    Adds the renovate configuration files to your repo so that renovate can start managing dependencies. 

  tags:
    - aws
    - renovate 
    - add
spec:
  owner: group:cds-snc/internal-sre
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          description: Name of the repository where you want renovate to be added
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            AllowedOrganizations:
              - cds-snc
            allowedOwners:
              - cds-snc

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"

    # Log the values
    - id: log values
      name: Log Values
      action: debug:log
      input:
        values:
          repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"

    # Create the PR and publish it to Github. 
    - id: renovate_pr 
      name: Create a Renovate PR
      action: publish:github:pull-request
      input:
       repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"
       allowedHosts: ["github.com"]
       branchName: "backstage_template_renovate"
       title: '🛠️ Add renovate dependency manager to your repo 🏥'
       description: |
          ## Renovate configuration addition.
            
          This is an initial pull request to add renovate configuration file to the repo so that Renovate can start managing your dependencies.
              
          *created by: [Backstage Software Template](https://github.com/cds-snc/backstage-scaffolder-templates/tree/main/templates/renovate)* 👷‍♂️⚙️👷‍♀️
       targetPath: "./"
    
  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: 'Go to pull request'
        icon: github