apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: terraform-vpc
  title: Create a VPC 
  description: |
    Creates the terrafrom code and infrastructure to add a VPC to your project. It uses CDS's terraform modules VPC infrastructure.

  tags:
    - terraform
    - aws
    - vpc
    - add
spec:
  owner: group:cds-snc/internal-sre
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in the VPC Details
      required:
        - vpc_name
        - billing_tag_value
        - high_availability
        - allow_https_requests_in
        - allow_https_requests_out
      properties:
        vpc_name:
          title: VPC Name
          type: string
          description: The name of the VPC. Required.
          ui:autofocus: true
        billing_tag_value:
          title: Billing tag Value 
          type: string
          description: The value of the billing tag for the VPC. Required. 
          ui:help: "Hint: This is probably already defined in your infrastructure, so look for the value in your existing infrastructure."
        high_availability:
          title: High Availability?
          type: boolean 
          description: Will the VPC have public and private subnets in multiple AWS availability zones making it more resilient to outages? Required.
          default: true
        allow_https_requests_in:
          title: Allow HTTPS Requests In?
          type: boolean 
          description: Should users and internet services be able to make requests to something running in the VPC and get a response? Required.
          default: true
        allow_https_requests_out:
          title: Allow HTTPS Requests Out?
          type: boolean 
          description: Is there a service running in the VPC that will be calling out to internet services and expect a response? Required.
          default: true 
        staging_or_production:
          title: Is this a staging or production service?
          type: boolean
          default: true
          description: Is this a staging or production service? If yes, we need to provide AWS Account ID. Required.
      dependencies:
        staging_or_production:
          allOf:
            - if:
                properties:
                  staging_or_production:
                    const: true
              then:
                properties:
                  account_id:
                    title: AWS Account ID 
                    type: string
                    description: The AWS Account ID where the VPC will be created. Required.
    
    - title: Choose a location
      required:
        - repoUrl
        - terraformLoc
      properties:
        repoUrl:
          title: Repository Location
          description: Name of the repository where the component will be stored
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            AllowedOrganizations:
              - cds-snc
            allowedOwners:
              - cds-snc
        terraformLoc:
            title: Terraform location 
            description: Location where you want the VPC terraform code to be stored 
            type: string
            ui:help: "Hint: This is the directory structure of where you want the VPC terraform files to live - for example terragrunt/aws/"


  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          vpc_name: ${{ parameters.vpc_name}}
          high_availability: ${{ parameters.high_availability}}
          allow_https_requests_in: ${{ parameters.allow_https_requests_in}}
          allow_https_requests_out: ${{ parameters.allow_https_requests_out}}
          availability_zones: ${{ 3 if parameters.high_availability else 1}}
          single_nat_gateway: ${{ 'false' if parameters.high_availability else 'true'}}
          allow_https_requests_in_response: ${{ 'true' if parameters.allow_https_requests_in else 'false'}}
          allow_https_requests_out_response: ${{ 'true' if parameters.allow_https_requests_out else 'false'}}
          staging_or_production: ${{ parameters.staging_or_production}}
          account_id: ${{ parameters.account_id}}
          cloud_based_sensor: ${{ 1 if parameters.staging_or_production else 0}}
          repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"
          billing_tag_value: ${{ parameters.billing_tag_value }}

    # Log the values
    - id: log values
      name: Log Values
      action: debug:log
      input:
        values:
          vpc_name: ${{ parameters.vpc_name}}
          high_availability: ${{ parameters.high_availability}}
          allow_https_requests_in: ${{ parameters.allow_https_requests_in}}
          allow_https_requests_out: ${{ parameters.allow_https_requests_out}}
          availability_zones: ${{ parameters.availability_zones}}
          allow_https_requests_in_response: ${{ parameters.allow_https_requests_in_response}}
          allow_https_requests_out_response: ${{ parameters.allow_https_requests_out_response}}
          staging_or_production: ${{ parameters.staging_or_production}}
          account_id: ${{ parameters.account_id}}
          repoUrl: "${{ parameters.repoUrl }}"
          billing_tag_value: ${{ parameters.billing_tag_value }}

    # Create the terraform PR and publish it to Github. 
    - id: terraform_pr
      name: Create terraform PR
      action: publish:github:pull-request
      input:
       repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"
       allowedHosts: ["github.com"]
       branchName: "backstage_template_vpc_${{ parameters.vpc_name}}"
       title: '⛅ Create ${{ parameters.vpc_name}} AWS VPC ☁️'
       description: |
          ## Creating VPC ${{ parameters.vpc_name }}
            
          This is an initial pull request to create a VPC and was created based on the Backstage template. 
              
          The terraform code is using cds's terraform mdodule for the VPC configuration. For more information, check the official documentation - https://github.com/cds-snc/terraform-modules/tree/main/vpc
   
          *created by: [Backstage Software Template](https://github.com/cds-snc/backstage-scaffolder-templates/tree/main/templates/vpc)* 👷‍♂️⚙️👷‍♀️
       targetPath: "${{ parameters.terraformLoc }}/vpc"
    
  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: 'Go to pull request'
        icon: github
      - title: 'To view more check documentation'
        icon: docs
        url: "https://github.com/cds-snc/terraform-modules/tree/main/vpc"