apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: hosted_zone
  title: Create a Hosted Zone
  description: |
    Creates the terrafrom code and infrastructure to add a hosted zone to your repo. 

  tags:
    - terraform
    - aws
    - hosted_zone 
    - add
spec:
  owner: group:cds-snc/internal-sre
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in the Hosted Zone Details
      required:
        - product_name 
        - billing_code 
      properties:
        product_name:
          title: What is the product name that you are creating the hosted zone for?
          type: string 
          description: The product name for the product for which you are creating the hosted zone for . Required.
        billing_code:
          title: Billing code 
          type: string
          description: The billing code to associate with the hosted zone. 

    - title: Choose a location
      required:
        - repoUrl
        - terraformLoc
      properties:
        repoUrl:
          title: Repository Location
          description: Name of the repository where the component will be stored
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            AllowedOrganizations:
              - cds-snc
            allowedOwners:
              - cds-snc
        terraformLoc:
            title: Terraform location 
            description: Location where you want the hosted zone terraform code to be stored 
            type: string
            ui:help: "Hint: This is the directory structure of where you want the hosted zone terraform files to live - for example terragrunt/aws/"


  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          product_name: ${{ parameters.product_name }}
          billing_code: ${{ parameters.billing_code }}
          repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"
          terraformLoc: ${{ parameters.terraformLoc }}

    # Log the values
    - id: log values
      name: Log Values
      action: debug:log
      input:
        values:
          product_name: ${{ parameters.product_name }}
          billing_code: ${{ parameters.billing_code }}
          repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"
          terraformLoc: ${{ parameters.terraformLoc }}

    # Create the terraform PR and publish it to Github. 
    - id: terraform_pr
      name: Create terraform PR
      action: publish:github:pull-request
      input:
       repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"
       allowedHosts: ["github.com"]
       branchName: "backstage_template_${{ parameters.product_name}}_hosted_zone"
       title: '🗃️ Create a hosted zone for ${{ parameters.product_name }} 🛜'
       description: |
          ## Creating a hosted zone for ${{ parameters.product_name }} 
            
          This is an initial pull request to create a hosted zone and was created based on a Backstage template. 
              
          *created by: [Backstage Software Template](https://github.com/cds-snc/backstage-scaffolder-templates/tree/main/templates/hosted_zone)* 👷‍♂️⚙️👷‍♀️
       targetPath: "${{ parameters.terraformLoc }}/hosted_zone"
    
  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: 'Go to pull request'
        icon: github