apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: project_template_bootstrap 
  title: Bootsrap a repo with project template github actions, LICENSE file and add a blank README.md
  description: |
    Bootstrap a repo with generic CDS github actions, LICENSE file and add a blank README.md. Creates the directory structure and adds the necessary files to get started. 

  tags:
    - add
    - bootstrap
    - aws
spec:
  owner: group:cds-snc/internal-sre
  type: service

  parameters:
    - title: Fill in Project Details
      properties:
        product_name:
          title: Product Name
          description: Name of the product that is to be bootstrapped 
          type: string
          ui:field: TextField
          ui:options:
            placeholder: 'Product Name'  

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          description: Name of the repository that is to be bootstrapped 
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            AllowedOrganizations:
              - cds-snc
            allowedOwners:
              - cds-snc

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        targetPath: ./content
        values:
            product_name: ${{ parameters.product_name }}
            repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"
            
    # Log the values
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: |
         "Project template has been bootstrapped to ${{ parameters.repoUrl }} with the following settings:"
          product_name: ${{ parameters.product_name }}
          repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"
    
    # Create the PR and publish it to Github. 
    - id: project_template_pr 
      name: Create Project Template PR
      action: publish:github:pull-request
      input:
       repoUrl: "github.com/cds-snc/${{ parameters.repoUrl }}"
       allowedHosts: ["github.com"]
       branchName: "backstage_project_template_bootstrap_template_${{ parameters.product_name }}"
       title: ' 🧬 Bootstrap Project template elements for ${{ parameters.product_name }} 🚀'
       description: |
          ## Bootstrapping project ${{ parameters.product_name }} with CDS project template elements 

          This is an initial pull request to add generic template specific github actions, LICENSE file and a blank README.md file. 
   
          *created by: [Backstage Software Template](https://github.com/cds-snc/backstage-scaffolder-templates/tree/main/templates/project_template)* 👷‍♂️⚙️👷‍♀️
       sourcePath: ./content
    
  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: 'Go to pull request'
        icon: github